name: Tag on PR Merge
on:
  pull_request:
    types:
      - closed

# So we can push the tag
permissions:
  contents: write

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
            ref: ${{ github.sha }}
            # Need last commit as well to view last semver tag
            fetch-depth: 2 
            fetch-tags: true
      - name: Get SemVer Bump Type
        id: bump-type
        uses: ./.github/actions/getBumpFromPr
        with:
          pr-description: ${{ github.event.pull_request.body }}
      - name: Tag Commit
        uses: ./.github/actions/tagCommit
        with:
          bumpType: ${{ steps.bump-type.outputs.bump-type }}
          sha: ${{ github.sha }}
