on:
  pull_request:
    types:
      - closed

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Tag Commit
        uses: ./.github/actions/print
        with:
          name: "pr-merged"