on:
  pull_request:
    types:
      - closed

# So we can push the tag
permissions:
  contents: write

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
            ref: ${{ github.sha }}
            # Need last commit as well to view last semver tag
            fetch-depth: 2 
            fetch-tags: true
      - name: Print
        uses: ./.github/actions/print
        with:
          name: "pr-merged"
      - name: Tag Commit
        uses: ./.github/actions/tagCommit
        with:
          versionType: PATCH # TODO: Parse this from the PR message
          sha: ${{ github.sha }}
