name: Checks
on:
  pull_request:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6
    - name: Print
      uses: ./.github/actions/print
      with:
        name: "pr"
  check-semver-bump:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6
    - name: Check SemVer Bump Type
      uses: ./.github/actions/getBumpFromPr
      with:
        pr-description: ${{ github.event.pull_request.body }}

